### ISSUE TITLE
what's the status for flannel on windows?

### ISSUE THREAD

**Issue by pablodav** [pablodav/kubernetes-for-windows#10]
@sebaxyz this  is the pull request to follow up: https://github.com/coreos/flannel/pull/921

**Comment by pablodav** [comment]
Some other updates related to followup:

https://github.com/containernetworking/plugins/pull/193

**Comment by pablodav** [comment]
Some news: https://github.com/coreos/flannel/pull/921#issuecomment-416688897

**Comment by pablodav** [comment]
related: https://github.com/pablodav/kubernetes-for-windows/issues/13

**Comment by ptylenda** [comment]
@pablodav looks like https://github.com/containernetworking/plugins/pull/193 has been merged. Unfortunately I will not have time to check it soon, at least for a few weeks..

**Comment by pablodav** [comment]
@ptylenda 
Looks like there are more work ongoing and fixes coming

https://github.com/Microsoft/SDN/pull/282
https://github.com/containernetworking/plugins/issues/80#issuecomment-440445609

I haven't checked yet what changes should I do to this role.

**Comment by daschott** [comment]
Also FYI https://github.com/coreos/flannel/pull/1042 has been merged.
