### ISSUE TITLE
Upgrade and support windows 2019

### ISSUE THREAD

**Issue by pablodav** [pablodav/kubernetes-for-windows#14]
* Deploy windows 2019 on test env
* change vars and docker download and prepare images on the role

**Comment by ashishtechie** [comment]
I tried using this for windows 2019 and after some fixes and changes i was able to run whole playbook but it didn't start the kubelet. Any idea on why would that be?

**Comment by pablodav** [comment]
I haven't tried with Windows 2019 yet, there are some changes pending in flannel too, I'm will try on next month
