### ISSUE TITLE
More devs working on this project

### ISSUE THREAD

**Issue by pablodav** [pablodav/kubernetes-for-windows#8]
@daschott
I see you have sent some work to merge in https://github.com/Microsoft/SDN/pull/231
I'm just informing you that I'm also working in this fork from @ptylenda to get something working to support k8s and windows. 
Could you have a look? 

Also https://github.com/kubernetes-incubator/kubespray/issues/2889 is related to this project.

**Comment by pablodav** [comment]
@damoxc I see in this pull request https://github.com/Microsoft/SDN/pull/232 you are working on same efforts as  mine in this project.

Could you have a look into this? 
I'm looking for more people working on same things to join efforts.

**Comment by ptylenda** [comment]
@pablodav @daschott @damoxc BTW I believe that the best thing we can do is to focus on kubespray implementation, this is probably the only place where windows support will be widely used and maintained by community. The problem is that kubespray has some significant "entry knowledge threshold" as it is a pretty big project. But if we manage to get to know the internals pretty well, then all the knowledge that is in all of our pull requests could be very useful there

**Comment by pablodav** [comment]
Yes, that is my final objective and this project is actually integrated with kubespray (using them in separate projects but working both together using submodules).

**Comment by pablodav** [comment]
You can see https://github.com/kubernetes-incubator/kubespray/pull/2956 as some effort to have a base to integrate this into kubespray.

**Comment by damoxc** [comment]
Integrating into kubespray looks like the right way to go, although I have no experience with it as yet. Happy to help out when I can, no point everyone doing their own thing!

**Comment by daschott** [comment]
Yes, integrating into kubespray would be awesome. It is finicky to deploy this stuff manually :)

One of the things that I'm wondering about @ptylenda in [Known Issues and Limitations](https://github.com/pablodav/kubernetes-for-windows#known-issues-and-limitations)

It states that outbound NAT is not possible unless pod-to-pod communication is disabled. Is this still accurate on Windows Server 1803? I find that both of this should work if I deployed [like this](https://1drv.ms/w/s!AgH65RVQdrbiglNr7P7P4VrO8Rxr)
